<a href="https://colab.research.google.com/github/AhnafIslamIO/summer-data-analytics-Microcredential/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Problems

____________

#### Import NumPy as np

In [6]:
import numpy as np
# Imported numpy into notebook

#### Create an array of 20 zeros 

In [7]:
np.zeros(20)
# created an array of 20 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Create an array of 10 ones

In [10]:
np.zeros(10)
# created an array of 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 fives

In [11]:
np.zeros(10)*5
# created an array of 10 fives

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of the integers from 10 to 50

In [13]:
np.arange(10,51)
# made an array of integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [14]:
np.arange(10,51, 2)
# made an array of even integers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
np.arange(0, 9).reshape(3,3)
# made an metrix with value range 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [17]:
np.eye(3)
# made an 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [19]:
np.random.rand(1)
# used numpy to generate random numbers between 0 to 1

array([0.81874997])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [20]:
np.random.randn(25)
# utilized numpy to create an array of 25 random numbers

array([-1.58651664,  0.88991975,  0.02166041,  0.13577591, -0.85840994,
        0.11694675,  1.40511368, -1.90064285, -0.7340837 ,  0.17228727,
       -1.19126166, -1.24433584,  0.52064405, -2.25793361,  0.47484852,
        1.45475652,  0.2178775 ,  0.87079428,  0.10319314, -1.4003453 ,
       -0.4320097 , -0.85014022,  0.01894477,  0.14412912,  0.39533016])

#### Create the following matrix:

In [22]:
np.arange(0.01,1.01,0.01).reshape(10,10)
# used numpy code to make a given matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [24]:
np.linspace(0,1,20)
# made an array of linear spaced of 20

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [25]:
import numpy as np
#mat = np.arange(1,27).reshape(5,5)
mat = np.arange(1,28).reshape(9,3)
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
array1 = np.arange(12, 16) 
array2 = np.arange(17, 21) 
array3 = np.arange(22, 26) 

arr = np.concatenate([array1, array2, array3]) 
arr.reshape(3, 4) 
# used the documentation(https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) + https://pythonguides.com/python-concatenate-arrays/ to concate

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [28]:
mat[6][1]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
arr = np.array([2, 7, 12]) # creating array containing 2,7,12
arr.reshape(3, 1) #reshaping it to 3 by 1 matrix

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
np.arange(21, 26)

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [31]:
array1 = np.arange(16, 26) #returns evenly spaced values btw 21 and 26
array1.reshape(2, 5) #reshaping it to 2 by 5 matrix

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now,

#### Get the sum of all the values in mat

In [32]:
mat = np.arange(1,28).reshape(9,3) # returns evenly spaced values btw 1 and 28(exclusive) + reshapes it into 9 by 3 matrix
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

#### Get the standard deviation of the values in mat

In [33]:
mat.std()

7.788880963698615

#### Get the sum of all the columns in mat

In [34]:
mat.sum(axis=1) # sums up the columns since axis 1 represents colmns

array([ 6, 15, 24, 33, 42, 51, 60, 69, 78])

# Cheers!